CC = g++
OBJS = main.o 
CFLAGS = 
PRG_NAME = run

$(PRG_NAME): $(OBJS)
	$(CC) $(CFLAGS) -o $(PRG_NAME) $(OBJS)

main.o: Puzzle1.h Puzzle2.h utils.h 

clean:
	rm $(OBJS) $(PRG_NAME)

sweep:
	rm $(OBJS)

		



